### ISSUE TITLE
Incorrect warping. Control Points not positioned accordingly

### ISSUE THREAD

**Issue by derMart** [timwaters/mapwarper#159]
It seems, the warping algorithm is incorrect. See the image below for the map http://mapwarper.net/maps/29903
![warp_error](https://user-images.githubusercontent.com/1069456/46295778-2cf93d80-c599-11e8-95d5-01cb08241fbe.jpg)

The control points on the left image should exactly match the historical map on the right side, but they are not.

**Comment by timwaters** [comment]
Thanks for taking the time to write this issue.

You can change the algorithm in the control panel. under advanced options.
![image](https://user-images.githubusercontent.com/48941/46301268-c4f92600-c59d-11e8-9704-5f038e99eeff.png)

Try selecting thin plate spline and see if that helps. Otherwise the default choice is to use a polynomial method.

**Comment by derMart** [comment]
Thank you very much. Yes, the TPS is working as expected.
Although, even if there are more than 25 control points, the automated method chooses a second order polynomial. From the descriptions I would assumed this to be 3rd order. As I haven't seen the advanced options in the first place, and as a novice user (like me in this case) I would expect the control points to match in any case, why not choosing TPS as default?

**Comment by timwaters** [comment]
TPS only really works well when the points are many and all spread out, and often failed. 

I am not sure how the gdalwarp program selects the method to use. From what I've found the numbers shown are the minimum amount of points needed for the method. One would expect 25 points to choose 3rd polynomial, yes!

**Comment by timwaters** [comment]
okay so apparently this is the correct location for that logic:

https://github.com/OSGeo/gdal/blob/master/gdal/alg/gdal_crs.c#L209

Note the comment: /*for now we avoid 3rd order since it is unstable*/

So we should expect 3rd polynomials to be used, but by default they won't be... I think I'll make a new issue for this.

**Comment by timwaters** [comment]
refs  #160
